add html content and modify it using css to add toolbar and headline section
Gedewon/Portfolio pull request #1
Opened 2022-02-16 22:36 UTC by Gedewon

## Portfolio Mobile skeleton
### In this milestone, I:
- Built the toolbar and headline section
- Used linters for code standard
- Used flex to parse Figma layout

2022-02-16 23:39 UTC, BenMukebo requested changes
### Hi **@gedewon**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight 💪🏻

- No linter errors. ✔️ 
- Github flow was correctly used.  ✔️   
- Good commit messages ✔️ 
- Professional README ✔️ 
- Descriptive PR.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 23:39 UTC, BenMukebo commented on index.html
> +    <header>
- [ ] Great work up to here, you have implemented HTML best practice, I salute your effort, I think now working on adding some improvement in the styling is crucial, see the image below and compare to the Figma design, please adjust your styling (`padding, colors, margins, font-weight, font-size, background`) to match as much as possible the original design
- [ ] Your design
<img width="235" alt="gede" src="https://user-images.githubusercontent.com/79058364/154375210-8cf531a8-213f-4cee-b4bd-0c72ed1157c2.png">

- [ ] Figma Design
<img width="252" alt="figgede" src="https://user-images.githubusercontent.com/79058364/154375504-75017a3b-67ea-4508-ae78-a5cb3aeea9be.png">

2022-02-18 12:04 UTC, prolajumokeoni commented on index.html
> +    <header>
-  Good job @Gedewon kindly make the header look like the original, so far you are on track 👏🏿 👏🏿 

##OPTIONAL


Your design             |  Figma Design
:-------------------------:|:-------------------------:
![bbbbbw](https://user-images.githubusercontent.com/69638013/154679571-e406d469-9c4c-46dd-8ac4-32d3ba2449f2.PNG)  | ![aaaaw](https://user-images.githubusercontent.com/69638013/154679463-3ea902ad-c7d4-4363-be5d-1050693f0abb.PNG)

- [ ] Kindly remove the border-bottom, change background colour and reduce padding to your design check screenshot above

2022-02-18 12:13 UTC, Gedewon commented on index.html
> +    <header>
@prolajumokeoni sure ,i am doing housekeeping for the Desktop version

2022-02-18 12:13 UTC, merged

2022-02-18 12:17 UTC, prolajumokeoni approved these changes
Hi @Gedewon 👋🏿 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_Check inline comments_
<br>
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification  @prolajumokeoni.
![153888587-3e47b8be-12ea-47db-a3c2-33122e091533](https://user-images.githubusercontent.com/69638013/154681427-4bd9ca32-1739-4edc-b069-371bce56d83c.gif)

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 12:17 UTC, prolajumokeoni commented on index.html
> +    <header>
- Ok great, keep rocking 💪🏿