add  work and about section
Gedewon/Portfolio pull request #2
Opened 2022-02-18 14:33 UTC by Gedewon

# in this pull request I added two basic components work and about me section 
### list of sections added :
- modifying index.html 
- add a section for the work
- add a section for the about section 
- - parsing the Figma design

2022-02-18 17:25 UTC, Gedewon commented on index.html
> +          <p class="let-connect">LET'S CONNECT</p>
@nicupop729 resolved

2022-02-18 17:46 UTC, codepantherr requested changes
Hi @Gedewon 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You have done well, but there are still a few changes you need to make to move forward.
<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 17:46 UTC, codepantherr commented on index.html
> +        <h2 class="let-connect">LET'S CONNECT</h2>
- [ ] This appears too big and makes your UI look clunky. Please follow the specification in the Figma template. The `font-size` should be `16px` 👍

2022-02-18 17:46 UTC, codepantherr commented on index.html
> +          <h2 class="let-connect">LET'S CONNECT</h2>
- [ ] Please see my comment above about this ☝️ .

2022-02-18 18:03 UTC, Gedewon commented on index.html
> +          <h2 class="let-connect">LET'S CONNECT</h2>
@codepantherr resolved

2022-02-19 14:16 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @Gedewon ,  

Your project is complete!  it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 14:23 UTC, merged

2022-02-20 08:49 UTC, Gedewon commented
this is my last project approved.so please check it I think you miss
understod me.I am not repeting the week okay.

On Sat, Feb 19, 2022 at 5:16 PM ShoiraTa ***@***.***> wrote:

> ***@***.**** approved this pull request.
> *STATUS: APPROVED ✔️*
> ------------------------------
>
> Hi @Gedewon <https://github.com/Gedewon> ,
>
> Your project is complete! it's time to merge it 🍾🚢 [image: :shipit:] .
> Congratulations! 🎉💯🌟
>
>
> <https://camo.githubusercontent.com/2f476fdf0117de3e4ceceffd092f5b112a2a13fc5dd243328b64fd987b920513/68747470733a2f2f7777772e73657269616c6d696e64732e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031352f31312f6c6f7365722e676966>
>
> Cheers and Happy coding! 👏 👏 👏
> Feel free to leave any questions or comments in the PR thread by
> mentioning my Github username if something is not 100% clear.
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have 2
> more limited reviews per this project. If you think that the code review
> was not fair, you can request a second opinion using this form
> <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Gedewon/Portfolio/pull/2#pullrequestreview-887929211>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANOQWKTEY7P6FDNRZOKHOR3U36Q33ANCNFSM5OYC56AA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>